/**
 * Carsales.Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { Http, Headers, URLSearchParams }                    from '@angular/http';
import { RequestMethod, RequestOptions, RequestOptionsArgs } from '@angular/http';
import { Response, ResponseContentType }                     from '@angular/http';

import { Observable }                                        from 'rxjs/Observable';
import 'rxjs/add/operator/map';

import * as models                                           from '../model/models';
import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class VehicleApi {

    protected basePath = 'http://localhost:6234';
    public defaultHeaders: Headers = new Headers();
    public configuration: Configuration = new Configuration();

    constructor(protected http: Http, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
        }
    }

    /**
     * 
     * @param input 
     * @param acceptLanguage Which languages the client is able to understand, and which locale variant is preferred. See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Language
     */
    public getBadgesAsync(input: models.GetBadgesInput, acceptLanguage?: string, extraHttpRequestParams?: any): Observable<Array<models.BadgeDto>> {
        return this.getBadgesAsyncWithHttpInfo(input, acceptLanguage, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json() || {};
                }
            });
    }

    /**
     * 
     * @param acceptLanguage Which languages the client is able to understand, and which locale variant is preferred. See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Language
     */
    public getMakesAsync(acceptLanguage?: string, extraHttpRequestParams?: any): Observable<Array<models.MakeDto>> {
        return this.getMakesAsyncWithHttpInfo(acceptLanguage, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json() || {};
                }
            });
    }

    /**
     * 
     * @param input 
     * @param acceptLanguage Which languages the client is able to understand, and which locale variant is preferred. See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Language
     */
    public getModelsAsync(input: models.GetModelsInput, acceptLanguage?: string, extraHttpRequestParams?: any): Observable<Array<models.ModelDto>> {
        return this.getModelsAsyncWithHttpInfo(input, acceptLanguage, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json() || {};
                }
            });
    }

    /**
     * 
     * @param input 
     * @param acceptLanguage Which languages the client is able to understand, and which locale variant is preferred. See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Language
     */
    public getVehiclesAsync(input: models.GetVehiclesInput, acceptLanguage?: string, extraHttpRequestParams?: any): Observable<models.PagedResultDtoVehicleDto> {
        return this.getVehiclesAsyncWithHttpInfo(input, acceptLanguage, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json() || {};
                }
            });
    }

    /**
     * 
     * @param input 
     * @param acceptLanguage Which languages the client is able to understand, and which locale variant is preferred. See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Language
     */
    public insertOrUpdateVehicle(input: models.VehicleDto, acceptLanguage?: string, extraHttpRequestParams?: any): Observable<models.VehicleDto> {
        return this.insertOrUpdateVehicleWithHttpInfo(input, acceptLanguage, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json() || {};
                }
            });
    }

    /**
     * 
     * @param acceptLanguage Which languages the client is able to understand, and which locale variant is preferred. See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Language
     */
    public isUserLoggedIn(acceptLanguage?: string, extraHttpRequestParams?: any): Observable<boolean> {
        return this.isUserLoggedInWithHttpInfo(acceptLanguage, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json() || {};
                }
            });
    }


    /**
     * 
     * 
     * @param input 
     * @param acceptLanguage Which languages the client is able to understand, and which locale variant is preferred. See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Language
     */
    public getBadgesAsyncWithHttpInfo(input: models.GetBadgesInput, acceptLanguage?: string, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + '/api/Vehicle/GetBadgesAsync';

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'input' is not null or undefined
        if (input === null || input === undefined) {
            throw new Error('Required parameter input was null or undefined when calling getBadgesAsync.');
        }
        if (acceptLanguage !== undefined && acceptLanguage !== null) {
            headers.set('Accept-Language', String(acceptLanguage));
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json',
            'text/json',
            'application/xml',
            'text/xml',
            'application/x-www-form-urlencoded'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json',
            'text/json',
            'application/xml',
            'text/xml'
        ];

        headers.set('Content-Type', 'application/json');

        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Post,
            headers: headers,
            body: input == null ? '' : JSON.stringify(input), // https://github.com/angular/angular/issues/10612
            search: queryParameters,
            withCredentials:this.configuration.withCredentials
        });
        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = (<any>Object).assign(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * 
     * 
     * @param acceptLanguage Which languages the client is able to understand, and which locale variant is preferred. See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Language
     */
    public getMakesAsyncWithHttpInfo(acceptLanguage?: string, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + '/api/Vehicle/GetMakesAsync';

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        if (acceptLanguage !== undefined && acceptLanguage !== null) {
            headers.set('Accept-Language', String(acceptLanguage));
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json',
            'text/json',
            'application/xml',
            'text/xml'
        ];

        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Get,
            headers: headers,
            search: queryParameters,
            withCredentials:this.configuration.withCredentials
        });
        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = (<any>Object).assign(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * 
     * 
     * @param input 
     * @param acceptLanguage Which languages the client is able to understand, and which locale variant is preferred. See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Language
     */
    public getModelsAsyncWithHttpInfo(input: models.GetModelsInput, acceptLanguage?: string, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + '/api/Vehicle/GetModelsAsync';

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'input' is not null or undefined
        if (input === null || input === undefined) {
            throw new Error('Required parameter input was null or undefined when calling getModelsAsync.');
        }
        if (acceptLanguage !== undefined && acceptLanguage !== null) {
            headers.set('Accept-Language', String(acceptLanguage));
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json',
            'text/json',
            'application/xml',
            'text/xml',
            'application/x-www-form-urlencoded'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json',
            'text/json',
            'application/xml',
            'text/xml'
        ];

        headers.set('Content-Type', 'application/json');

        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Post,
            headers: headers,
            body: input == null ? '' : JSON.stringify(input), // https://github.com/angular/angular/issues/10612
            search: queryParameters,
            withCredentials:this.configuration.withCredentials
        });
        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = (<any>Object).assign(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * 
     * 
     * @param input 
     * @param acceptLanguage Which languages the client is able to understand, and which locale variant is preferred. See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Language
     */
    public getVehiclesAsyncWithHttpInfo(input: models.GetVehiclesInput, acceptLanguage?: string, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + '/api/Vehicle/GetVehiclesAsync';

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'input' is not null or undefined
        if (input === null || input === undefined) {
            throw new Error('Required parameter input was null or undefined when calling getVehiclesAsync.');
        }
        if (acceptLanguage !== undefined && acceptLanguage !== null) {
            headers.set('Accept-Language', String(acceptLanguage));
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json',
            'text/json',
            'application/xml',
            'text/xml',
            'application/x-www-form-urlencoded'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json',
            'text/json',
            'application/xml',
            'text/xml'
        ];

        headers.set('Content-Type', 'application/json');

        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Post,
            headers: headers,
            body: input == null ? '' : JSON.stringify(input), // https://github.com/angular/angular/issues/10612
            search: queryParameters,
            withCredentials:this.configuration.withCredentials
        });
        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = (<any>Object).assign(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * 
     * 
     * @param input 
     * @param acceptLanguage Which languages the client is able to understand, and which locale variant is preferred. See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Language
     */
    public insertOrUpdateVehicleWithHttpInfo(input: models.VehicleDto, acceptLanguage?: string, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + '/api/Vehicle/InsertOrUpdateVehicle';

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'input' is not null or undefined
        if (input === null || input === undefined) {
            throw new Error('Required parameter input was null or undefined when calling insertOrUpdateVehicle.');
        }
        if (acceptLanguage !== undefined && acceptLanguage !== null) {
            headers.set('Accept-Language', String(acceptLanguage));
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json',
            'text/json',
            'application/xml',
            'text/xml',
            'application/x-www-form-urlencoded'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json',
            'text/json',
            'application/xml',
            'text/xml'
        ];

        headers.set('Content-Type', 'application/json');

        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Post,
            headers: headers,
            body: input == null ? '' : JSON.stringify(input), // https://github.com/angular/angular/issues/10612
            search: queryParameters,
            withCredentials:this.configuration.withCredentials
        });
        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = (<any>Object).assign(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * 
     * 
     * @param acceptLanguage Which languages the client is able to understand, and which locale variant is preferred. See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Language
     */
    public isUserLoggedInWithHttpInfo(acceptLanguage?: string, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + '/api/Vehicle/IsUserLoggedIn';

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        if (acceptLanguage !== undefined && acceptLanguage !== null) {
            headers.set('Accept-Language', String(acceptLanguage));
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json',
            'text/json',
            'application/xml',
            'text/xml'
        ];

        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Get,
            headers: headers,
            search: queryParameters,
            withCredentials:this.configuration.withCredentials
        });
        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = (<any>Object).assign(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

}
