/**
 * Carsales.Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface BadgeDto {
    name?: string;

    modelId?: number;

    model?: models.ModelDto;

    vehicleType?: BadgeDto.VehicleTypeEnum;

    id?: number;

}
export namespace BadgeDto {
    export enum VehicleTypeEnum {
        NUMBER_1 = <any> 1,
        NUMBER_2 = <any> 2
    }
}
