/**
 * Carsales.Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface ModelDto {
    name?: string;

    makeId?: number;

    make?: models.MakeDto;

    vehicleType?: ModelDto.VehicleTypeEnum;

    id?: number;

}
export namespace ModelDto {
    export enum VehicleTypeEnum {
        NUMBER_1 = <any> 1,
        NUMBER_2 = <any> 2
    }
}
